version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-request-limit: 100
    registries: "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
