language: go
sudo: false

cache:
  directories:
    - $GOPATH/pkg/mod

git:
  depth: 1

env:
  - GO111MODULE=on

matrix:
  fast_finish: true
  include:
    - go: 1.14.x
    - go: 1.15.x
    - go: 1.16.x
    - go: tip
  allow_failures:
    - go: tip

before_script:
  - go mod download

script:
  - go test ./...
  - go test -race ./...
