---

name: toxiproxy

type: go

up:
  - homebrew:
      - gnu-tar
      - golangci-lint
      - goreleaser
      - shellcheck
      - shfmt
      - yamllint
  - go:
      version: 1.18
      modules: true
