name: toxiproxy

type: go

up:
  - homebrew:
    - gnu-tar
  - go:
      version: 1.16
      modules: true
  - ruby: 3.0.2
  - bundler

commands:
  build:
    run: go build ./...
    desc: 'build the project'
  test:
    run: go test ./...
    desc: 'run unit tests'
