---

name: toxiproxy

type: go

up:
  - packages:
      - gnu-tar
      - golangci-lint
      - goreleaser
      - shellcheck
      - shfmt
      - yamllint
  - go:
      version: 1.22.1
      modules: true
