name: toxiproxy

type: go

up:
  - homebrew:
    - openssl
    - gnu-tar
  - go:
      version: 1.12
      modules: true
  - ruby: 2.6.3
  - bundler

commands:
  build:
    run: go build ./...
    desc: 'build the project'
  test:
    run: go test ./...
    desc: 'run unit tests'
