name: push-release-pipeline
on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Install golang
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      # Checkout to the latest commit
      # On specific directory/path
      - name: Checkout
        uses: actions/checkout@v2

      - name: gofmt check
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -ne 0 ]
          then
          echo "The following files were found to be not go formatted:"
          gofmt -s -l .
          exit 1
          fi

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1

      - name: unused-package check
        run: |
          make unused-package-check


      - name: Building toxiproxy
        run: |
          make build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Copy binaries to the toxiproxy s3 bucket
        run: |
          aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET }}
